//Customer Action Types
export const REDDIT_BEGIN_FETCH = 'REDDIT_BEGIN_FETCH';
export const REDDIT_FETCHED_DATA = 'REDDIT_FETCHED_DATA';
export const REDDIT_ERROR_FETCH = 'REDDIT_ERROR_FETCH';
export const REDDIT_SELECT_ITEM = 'REDDIT_SELECT_ITEM';
export const REDDIT_REMOVE_ITEM = 'REDDIT_REMOVE_ITEM';
export const REDDIT_REMOVING_ITEM = 'REDDIT_REMOVING_ITEM';
export const REDDIT_REMOVE_ALL_ITEMS = 'REDDIT_REMOVE_ALL_ITEMS';